CREATE TABLE events(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_event VARCHAR(30) NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX fx_events_status ON events(status_event);

CREATE TABLE events_outbox(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT NOW(),
    retry_count INT DEFAULT 0,
    next_retry_at TIMESTAMP NULL,
    last_error TEXT NULL,
    processed_at TIMESTAMP,
    processing_started_at TIMESTAMP
);

CREATE INDEX idx_outbox_unprocessed
    ON events_outbox(status, created_at)
    WHERE status = 'PENDING';